### PR TITLE
Bump containers upper dependency bound

### PR DESCRIPTION
**Pull request by erikd**
ghc-9.10 requires containers == 0.7.*

### CODE REVIEW

**Review by wraithm — APPROVED** [review]

**Comment by wraithm** [comment]
Thank you!

**Comment by erikd** [comment]
@wraithm A Hackage metadata edit would be much appreciated too.

**Comment by wraithm** [comment]
> @wraithm A Hackage metadata edit would be much appreciated too.

I will do that tomorrow 🫡

**Comment by wraithm** [comment]
@erikd I uploaded 2.3.0 to hackage 👍🏻

**Pull request merged**
