### PR TITLE
Bumped deps, fixed errors

### PR DESCRIPTION
**Pull request by schell**
This bumps the deps of `proto-lens` and friends. I followed the compiler errors and patched them up.

### CODE REVIEW

**Comment by WraithM** [comment]
`OverloadedLabels` and `TypeApplications` forces users into using GHC 8 and higher. Are there other things in this repo that force GHC 8? It might be worth while to figure out if we can upgrade these packages and still keep backwards compatibility with GHC 7. Though, if this package is already forcing GHC 8, then I don't have a problem with going all-in on GHC 8.

**Comment by schell** [comment]
`TypeApplications` can be worked around but `proto-lens` depends on `lens-labels` which is all about `OverloadedLabels`. `proto-lens-protoc` generates lenses to use through `OverloadedLabels` so I don't think there's an easy way to maintain GHC 7/8 interop _and_ relax upper bounds on deps. 

Though it is easy enough for downstream libraries to pin their deps to previous versions if they are required to work with GHC 7.

**Comment by WraithM** [comment]
Interesting. Looks like we'd need to rewrite this part of the code without using `proto-lens` to get GHC 7 support then. @lukehoersten What do you think?

**Comment by lukehoersten** [comment]
@WraithM agreed we should remove lenses. If you look at the other open PRs, there's continued attempts to keep this working on GHC 7. Also, lens increases memory requirements on the build making it harder to build on cheap AWS/DO instances.

Remember in prometheus 2+, protobuf is deprecated:
https://prometheus.io/docs/instrumenting/exposition_formats/

If anything we should upgrade to 2.0 text format.

**Comment by schell** [comment]
Sound good to me. Less dependencies are better IMO.

**Comment by schell** [comment]
Is there a timeline or someone who's willing to spearhead the effort? I'd venture on my own but I don't have the history nor the long term goals of the project in mind.

**Comment by lukehoersten** [comment]
Thanks for the PR @schell - if for some reason we end up keeping protobufs, we can reopen this.

**Pull request closed without merging**
